Allow multiline input in chat box
SSWConsulting/SSW.Rules.GPT pull request #87
Opened 2023-06-21 03:01 UTC by jackreimers

Closes #79 

The chat input now allows multiple lines and responds to Shift + Enter.
Had to use JS to achieve this due to the way MudBlazor handles its text field internally, if 'Lines' is set to 1 on the MudTextField it uses a standard input tag which will not respond to multiline input, and only uses a textarea if it is set to >1.

The maximum height for the input is set at 5 rows.

![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/10693364/bcaeae80-3ccc-44a3-a33d-696919ab6451)

2023-06-21 03:42 UTC, bradystroud commented
Finally 🤍

2023-06-22 06:13 UTC, bradystroud requested changes
🤦🏻‍♂️

2023-06-22 06:13 UTC, bradystroud commented on src/WebUI/wwwroot/index.html
> +            input = document.querySelector('.chat-input textarea');
```suggestion
input = document.getElementById('chat-input').querySelector('textarea');
```

2023-06-22 22:31 UTC, bradystroud approved these changes

2023-06-22 23:02 UTC, Harry-Ross approved these changes
lgtm

2023-06-22 23:57 UTC, merged